"""
SUTRIX Thesis Preliminary Pages
Contains metadata and content for front matter (title, certificates, declaration, abstract, abbreviations).
"""

METADATA = {
    "title": "SUTRIX: A Regulatory-Grade Scientific Data Orchestration Platform for Transparent Harmonization, Hierarchical Data Engineering, and QSAR Workflow Readiness Assessment",
    "candidate": "Arghya Ghosh",
    "degree": "Bachelor of Pharmacy (B.Pharm.)",
    "department": "Department of Pharmaceutical Chemistry",
    "institution": "Bharat Technology",
    "university": "Maulana Abul Kalam Azad University of Technology (MAKAUT), West Bengal",
    "supervisor": "Dr. Mainak Chatterjee",
    "supervisor_designation": "Associate Professor",
    "year": "2025-2026",
    "location": "West Bengal, India"
}

CONTENT = [
    ("title_page", METADATA),
    ("page_break",),
    ("h1", "Supervisor Certificate"),
    ("p", "This is to certify that the thesis entitled \"SUTRIX: A Regulatory-Grade Scientific Data Orchestration Platform for Transparent Harmonization, Hierarchical Data Engineering, and QSAR Workflow Readiness Assessment\" submitted by Arghya Ghosh, in partial fulfillment of the requirements for the award of Bachelor of Pharmacy (B.Pharm.), is a record of bonafide research work carried out by him under my supervision and guidance. The results embodied in this thesis have not been submitted to any other University or Institute for the award of any degree or diploma."),
    ("p", "In my opinion, the thesis is of standard required for the award of the degree of Bachelor of Pharmacy. I recommend the thesis for evaluation and oral defense."),
    ("p", "\n\n___________________________________\nDr. Mainak Chatterjee\nAssociate Professor\nDepartment of Pharmaceutical Chemistry\nBharat Technology\nMaulana Abul Kalam Azad University of Technology (MAKAUT), West Bengal\nDate: June 15, 2026"),
    ("page_break",),
    ("h1", "Declaration by Candidate"),
    ("p", "I, Arghya Ghosh, hereby declare that the research work presented in this thesis entitled \"SUTRIX: A Regulatory-Grade Scientific Data Orchestration Platform for Transparent Harmonization, Hierarchical Data Engineering, and QSAR Workflow Readiness Assessment\" is my own original work. This work was carried out at the Department of Pharmaceutical Chemistry, Bharat Technology, under the supervision of Dr. Mainak Chatterjee."),
    ("p", "I have not submitted the matter embodied in this thesis for the award of any other degree or diploma to Maulana Abul Kalam Azad University of Technology (MAKAUT) or any other institution. I have faithfully acknowledged and cited all references and sources used in this work. I take full responsibility for the content, scientific validity, and integrity of this dissertation."),
    ("p", "\n\n___________________________________\nArghya Ghosh\nDepartment of Pharmaceutical Chemistry\nBharat Technology\nDate: June 15, 2026"),
    ("page_break",),
    ("h1", "Acknowledgements"),
    ("p", "First and foremost, I would like to express my deepest gratitude to my supervisor, Dr. Mainak Chatterjee, Associate Professor, Department of Pharmaceutical Chemistry, Bharat Technology, for his invaluable guidance, constant encouragement, and insightful feedback throughout this project. His deep knowledge of pharmaceutical biotechnology, cheminformatics, and regulatory science has been a guiding light for this research."),
    ("p", "I wish to thank the faculty members and staff of the Department of Pharmaceutical Chemistry and the Computer Laboratories at Bharat Technology for providing the computational resources. Special thanks go to the Open Source Software community, especially the developers of RDKit, FastAPI, React, and Python, whose hard work made the tools used in this project freely available."),
    ("p", "Lastly, I want to thank my parents, my family, and my friends for their endless support, patience, and love. Their presence and belief in me kept me going during the late nights and weekends spent compiling this code and thesis."),
    ("page_break",),
    ("h1", "Abstract"),
    ("p", "In regulatory ecotoxicology and drug discovery, Quantitative Structure-Activity Relationship (QSAR) models serve as primary alternatives to animal testing, directly supporting regulatory filings under frameworks like REACH and OECD guidelines. However, heterogeneous public data repositories suffer from severe duplicate observations, conflicting endpoint measures, and missing experimental metadata. These issues create a reproducibility crisis, undermining trust in QSAR models. SUTRIX is a regulatory-grade scientific data orchestration platform designed to address these challenges by providing transparent, user-controlled data harmonization, hierarchical taxonomic segregation, and automated OECD readiness assessment."),
    ("p", "SUTRIX utilizes a modular compiler architecture that implements a strict front-end/back-end segregation. The front-end is built with React and TypeScript, leveraging Zustand for real-time workspace state management and snapshot persistence. The back-end is powered by FastAPI, deploying an SQLite session registry for metadata auditing, and SQLite caching for high-performance parquet data storage. The core scientific engine provides five distinct group variance curation strategies (including KEEP_ALL, KEEP_MEDIAN, and REMOVE_CONFLICTS) and four structural duplicate resolving strategies based on RDKit canonical SMILES and InChI keys. SUTRIX automatically performs taxonomic and experimental endpoint segregation, creating a clear tree hierarchy (using NetworkX graphs) and calculating applicability domain matrices (using Hat matrices and leverage limits)."),
    ("p", "SUTRIX was verified using three distinct validation datasets. A demonstration dataset (90 rows) showed a successful reduction to 55 harmonized records. A synthetic validation dataset verified the mathematical accuracy of the deduplication and variance filters. A stress dataset containing 10,000 compounds was processed in 39.8 seconds, demonstrating high scalability. End-to-end (E2E) testing with Playwright (41/41 passing tests) confirmed the absolute integrity of state persistence and UI operations under load. SUTRIX represents a major step forward in regulatory-grade cheminformatics platforms, enabling reproducible, audit-tracked, and explainable chemical datasets for predictive toxicology."),
    ("p", "\nKeywords: QSAR, Cheminformatics, Regulatory Science, Ecotoxicology, Data Harmonization, Playwright, React, FastAPI, RDKit, Applicability Domain"),
    ("page_break",),
    ("h1", "List of Abbreviations"),
    ("table", ["Abbreviation", "Definition"], [
        ["AD", "Applicability Domain"],
        ["AGPL", "GNU Affero General Public License"],
        ["AOP", "Adverse Outcome Pathway"],
        ["API", "Application Programming Interface"],
        ["CAS", "Chemical Abstracts Service"],
        ["ChEMBL", "Chemical Database of the European Molecular Biology Laboratory"],
        ["COV", "Coefficient of Variation"],
        ["CSV", "Comma Separated Values"],
        ["DOM", "Document Object Model"],
        ["E2E", "End-to-End"],
        ["ECHA", "European Chemicals Agency"],
        ["EPA", "Environmental Protection Agency (US)"],
        ["FK", "Foreign Key"],
        ["GNN", "Graph Neural Network"],
        ["HTTP", "Hypertext Transfer Protocol"],
        ["IC50", "Half Maximal Inhibitory Concentration"],
        ["InChI", "IUPAC International Chemical Identifier"],
        ["LC50", "Lethal Concentration, 50%"],
        ["LD50", "Lethal Dose, 50%"],
        ["LFER", "Linear Free Energy Relationship"],
        ["LOAEL", "Lowest Observed Adverse Effect Level"],
        ["LOEC", "Lowest Observed Effect Concentration"],
        ["ML", "Machine Learning"],
        ["MW", "Molecular Weight"],
        ["NOAEL", "No Observed Adverse Effect Level"],
        ["NOEC", "No Observed Effect Concentration"],
        ["OECD", "Organisation for Economic Co-operation and Development"],
        ["OPERA", "Open Structure-activity Relationship App"],
        ["PK", "Primary Key"],
        ["QSAR", "Quantitative Structure-Activity Relationship"],
        ["REACH", "Registration, Evaluation, Authorisation and Restriction of Chemicals"],
        ["REST", "Representational State Transfer"],
        ["SDF", "Structure Data File"],
        ["SUTRIX", "Scientific User-controlled Transparent Reduction and Integration eXchange"],
        ["TOC", "Table of Contents"],
        ["UUID", "Universally Unique Identifier"],
        ["WS", "WebSockets"],
        ["ZUSTAND", "Simple, fast, and scaleable state management library for React"]
    ], "Table P.1: List of Scientific and Technical Abbreviations used in the Thesis")
]
