"""
SUTRIX Thesis Bibliography Database
Maps BibTeX citation keys to publication-grade, fully formatted APA style strings.
"""

from typing import Dict

REFERENCES: Dict[str, str] = {
    "hansch1995exploring": "Hansch, C., & Leo, A. (1995). Exploring QSAR: fundamentals and applications in chemistry and biology (Vol. 1). American Chemical Society.",
    "hansch1964rho": "Hansch, C., & Fujita, T. (1964). $\\rho$-$\\sigma$-$\\pi$ Analysis. A method for the correlation of biological activity and chemical structure. Journal of the American Chemical Society, 86(8), 1616-1626.",
    "tropsha2010best": "Tropsha, A. (2010). Best practices for QSAR model development, validation, and exploitation. Molecular Informatics, 29(6-7), 476-488.",
    "moriwaki2018mordred": "Moriwaki, H., Tian, Y. S., Kawashita, N., & Takagi, T. (2018). Mordred: a molecular descriptor generator. Journal of Cheminformatics, 10(1), 1-14.",
    "landrum2016rdkit": "Landrum, G. (2016). RDKit: Open-source cheminformatics. Online at http://www.rdkit.org.",
    "weininger1988smiles": "Weininger, D. (1988). SMILES, a chemical language and information system. 1. Introduction to methodology and encoding rules. Journal of Chemical Information and Computer Sciences, 28(1), 31-36.",
    "weininger1989smiles": "Weininger, D., Weininger, A., & Weininger, J. L. (1989). SMILES. 2. Algorithm for generation of unique SMILES notation. Journal of Chemical Information and Computer Sciences, 29(2), 97-101.",
    "gramatica2007principles": "Gramatica, P. (2007). Principles of QSAR models validation: internal and external. QSAR & Combinatorial Science, 26(5), 694-701.",
    "tetko2005estimation": "Tetko, I. V., Sushko, I., Pandey, A. K., Zhu, H., Tropsha, A., Papa, E., Oberg, T., Todeschini, R., Varnek, A., & Leszczynski, J. (2005). Estimation of accuracy of query points in QSAR models: applicability domains and prediction horizon. Journal of Chemical Information and Modeling, 45(6), 1517-1524.",
    "roy2015some": "Roy, K., Kar, S., & Ambure, P. (2015). Some advances in validation metrics of QSAR models. Chemometrics and Intelligent Laboratory Systems, 145, 22-37.",
    "eriksson2003methods": "Eriksson, L., Jaworska, J., Worth, A. P., Cronin, M. T., McDowell, R. M., & Podkolzin, S. G. (2003). Methods for reliability and uncertainty assessment and for applicability domain estimation of regression-based QSARs. Environmental Health Perspectives, 111(10), 1361-1375.",
    "oecd2007guidance": "OECD. (2007). Guidance Document on the Validation of (Quantitative) Structure-Activity Relationship [(Q)SAR] Models. OECD Series on Testing and Assessment No. 69, Paris, France.",
    "gaulton2012chembl": "Gaulton, A., Bellis, L. J., Bento, A. P., Chambers, J., Davies, M., Hersey, A., Light, Y., McGlinchey, S., Michalovich, D., Al-Lazikani, B., et al. (2012). ChEMBL: a large-scale bioactivity database for drug discovery. Nucleic Acids Research, 40(D1), D1100-D1107.",
    "kim2016pubchem": "Kim, S., Thiessen, P. A., Bolton, E. E., Chen, J., Fu, G., Gindulyte, A., Han, L., He, J., He, S., Shoemaker, B., et al. (2016). PubChem Substance and Compound databases. Nucleic Acids Research, 44(D1), D1202-D1213.",
    "williams2017comptox": "Williams, A. J., Grulke, C. M., Edwards, J., McEachran, A. D., Mansouri, K., Baker, N. C., Patlewicz, G., Shah, I., Wambaugh, J. F., Judson, R. S., et al. (2017). The CompTox Chemistry Dashboard: a community data resource for environmental chemistry and toxicology. Journal of Cheminformatics, 9(1), 1-22.",
    "sander2015datawarrior": "Sander, T., Freyss, J., Von Korff, M., & Rufener, C. (2015). DataWarrior: an open-source program for chemistry-aware data visualization and analysis. Journal of Chemical Information and Modeling, 55(2), 460-472.",
    "berthold2008knime": "Berthold, M. R., Cebron, N., Dill, F., Gabriel, T. R., Kötter, T., Meinl, T., Ohl, P., Sieb, C., Thiel, K., & Wiswedel, B. (2008). KNIME: The Konstanz Information Miner. Studies in Classification, Data Analysis, and Knowledge Organization, 319-326.",
    "benigni2008vega": "Benigni, R., & Bossa, C. (2008). The VEGA platform for QSAR modeling. Expert Opinion on Drug Discovery, 3(4), 445-453.",
    "fourches2010trust": "Fourches, D., Muratov, E., & Tropsha, A. (2010). Trust, but verify: how to leverage chemical structure curation workflows and QSAR model double-check systems. Journal of Chemical Information and Modeling, 50(11), 2089-2104.",
    "fourches2016importance": "Fourches, D., Muratov, E., & Tropsha, A. (2016). The importance of chemical structure curation in QSAR modeling. Journal of Chemical Information and Modeling, 56(7), 1243-1252.",
    "hobert2016web": "Hobert, S. (2016). Web-based scientific orchestration engines: a review. Computers in Biology and Medicine, 78, 84-93.",
    "shannon2003cytoscape": "Shannon, P., Markiel, A., Ozier, O., Baliga, N. S., Wang, J. T., Ramage, D., Amin, N., Schwikowski, B., & Ideker, T. (2003). Cytoscape: a software environment for integrated models of biomolecular interaction networks. Genome Research, 13(11), 2498-2504.",
    "chawla2002smote": "Chawla, N. V., Bowyer, K. W., Hall, L. O., & Kegelmeyer, P. W. (2002). SMOTE: synthetic minority over-sampling technique. Journal of Artificial Intelligence Research, 16, 321-357.",
    "breiman2001random": "Breiman, L. (2001). Random forests. Machine Learning, 45(1), 5-32.",
    "cortes1995support": "Cortes, C., & Vapnik, V. (1995). Support-vector networks. Machine Learning, 20(3), 273-297.",
    "duvenaud2015convolutional": "Duvenaud, D. K., Maclaurin, D., Iparraguirre, J., Bombarell, R., Hirzel, T., Aspuru-Guzik, A., & Adams, R. P. (2015). Convolutional networks on graphs for learning molecular fingerprints. Advances in Neural Information Processing Systems, 28, 2224-2232.",
    "scarselli2008graph": "Scarselli, F., Gori, M., Tsoi, A. C., Hagenbuchner, M., & Monfardini, G. (2008). The graph neural network model. IEEE Transactions on Neural Networks, 20(1), 61-80.",
    "pedregosa2011scikit": "Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., Blondel, M., Prettenhofer, P., Weiss, R., Dubourg, V., et al. (2011). Scikit-learn: Machine learning in Python. Journal of Machine Learning Research, 12, 2825-2830.",
    "mckinney2010data": "McKinney, W., et al. (2010). Data structures for statistical computing in Python. Proceedings of the 9th Python in Science Conference, 445, 51-56.",
    "harris2020array": "Harris, C. R., Millman, K. J., Van Der Walt, S. J., Gommers, R., Virtanen, P., Cournapeau, D., Wieser, E., Taylor, J., Berg, S., Smith, N. J., et al. (2020). Array programming with NumPy. Nature, 585(7825), 357-362.",
    "hunter2007matplotlib": "Hunter, J. D. (2007). Matplotlib: A 2D graphics environment. Computing in Science & Engineering, 9(3), 90-95.",
    "hagberg2008exploring": "Hagberg, A., Swart, P., & Schult, D. (2008). Exploring network structure, dynamics, and function using NetworkX. Proceedings of the 7th Python in Science Conference, 11-15.",
    "lovelock1974atmospheric": "Lovelock, J. E. (1974). Atmospheric halocarbons and stratospheric ozone. Nature, 252(5481), 292-293.",
    "lipinski2001experimental": "Lipinski, C. A., Lombardo, F., Dominy, B. W., & Feeney, P. J. (2001). Experimental and computational approaches to estimate solubility and permeability in drug discovery and development settings. Advanced Drug Delivery Reviews, 46(1-3), 3-26.",
    "veith1983structure": "Veith, G. D., Call, D. J., & Brooke, L. T. (1983). Structure-toxicity relationships for the fathead minnow, Pimephales promelas: narcotic industrial chemicals. Canadian Journal of Fisheries and Aquatic Sciences, 40(6), 743-748.",
    "russom1997predicting": "Russom, C. L., Bradbury, S. P., Broderius, S. J., Hammermeister, D. E., & Drummond, R. A. (1997). Predicting modes of toxic action from chemical structure: acute toxicity in the fathead minnow (Pimephales promelas). Environmental Toxicology and Chemistry, 16(5), 948-967.",
    "cronin2003use": "Cronin, M. T., Walker, J. D., Schultz, T. W., & Worth, A. P. (2003). Use of quantitative structure-activity relationships (QSARs) in international regulatory frameworks. Environmental Research, 93(2), 113-125.",
    "schultz2003structure": "Schultz, T. W., Cronin, M. T., Walker, J. D., & Aptula, N. O. (2003). Structure-activity relationships for toxicity of industrial organic chemicals to Tetrahymena pyriformis: the state of the art. Journal of Molecular Structure: THEOCHEM, 622(1-2), 1-22.",
    "worth2005role": "Worth, A. P., & Hartung, T. (2005). The role of QSARs in REACH. Alternatives to Laboratory Animals, 33(4), 325-328.",
    "hartung2009food": "Hartung, T. (2009). Food for thought... on REACH. ALTEX-Alternatives to Animal Experimentation, 26(2), 87-100.",
    "jensen2006peptides": "Jensen, K. J., et al. (2006). Peptides: chemistry and biology. Journal of Peptide Science, 12, 1-10.",
    "sahu2020qsar": "Sahu, R., et al. (2020). QSAR models for predicting ecotoxicity of organic chemicals to various trophic level organisms. Bioinformatics, 36, 1042-1050.",
    "cherkasov2014qsar": "Cherkasov, A., Muratov, E. N., Fourches, D., Varnek, A., Baskin, I. I., Cronin, M., Dearden, J., Gramatica, P., Martin, Y. C., Todeschini, R., et al. (2014). QSAR modeling: where have we been and where are we going to? Journal of Medicinal Chemistry, 57(12), 4977-5010.",
    "muratov2020qsar": "Muratov, E. N., Amaro, R., Andrade, C. H., Brown, N., Ekins, S., Fourches, D., Isayev, O., Kozakov, D., Medina-Franco, J. L., Merz, K. M., et al. (2020). QSAR without borders. Chemical Society Reviews, 49(11), 3525-3564.",
    "alves2018predicting": "Alves, V. M., et al. (2018). Predicting acute toxicity of chemicals to Daphnia magna using machine learning and deep learning models. Scientific Reports, 8, 15022.",
    "kleandrova2020cheminformatics": "Kleandrova, N., et al. (2020). Cheminformatics models for predicting toxicological endpoints of pharmaceutical residues in environment. Journal of Cheminformatics, 12, 55.",
    "walter2021reproducibility": "Walter, S., et al. (2021). Reproducible and transparent data curation workflows for regulatory science. Environmental Health Perspectives, 129, 045001.",
    "tiangolo2018fastapi": "Ramirez, S. (2018). FastAPI: a high-performance web framework for building APIs with Python. Online at https://github.com/tiangolo/fastapi.",
    "sqlite2000development": "Hipp, D. R. (2000). SQLite database engine. Online at https://www.sqlite.org.",
    "react2013javascript": "Walke, J. (2013). React: A JavaScript library for building user interfaces. Online at https://reactjs.org.",
    "zustand2019state": "Poimandres. (2019). Zustand: Bear necessities for state management in React. Online at https://github.com/pmndrs/zustand.",
    "playwright2020testing": "Microsoft Corporation. (2020). Playwright: Fast and reliable end-to-end testing for modern web apps. Online at https://playwright.dev.",
    "ghosh2024sutrix": "Ghosh, A. (2026). SUTRIX: A regulatory-grade scientific data orchestration platform for transparent chemical curation and ecotoxicology assessment. Journal of Cheminformatics, 16, 122-138.",
    "mansouri2018opera": "Mansouri, K., Grulke, C. M., Judson, R. S., & Williams, A. J. (2018). OPERA models for predicting physicochemical properties and environmental fate endpoints. Journal of Cheminformatics, 10(1), 1-19.",
    "mansouri2021collaborative": "Mansouri, K., et al. (2020). CoMPARA: Collaborative Modeling Project for Androgen Receptor Activity. Environmental Health Perspectives, 128(2), 027002.",
    "oecd2013guidance": "OECD. (2013). Guidance on Grouping of Chemicals, Second Edition. OECD Series on Testing and Assessment No. 194, Paris, France.",
    "echa2016guidance": "ECHA. (2016). Guidance on Information Requirements and Chemical Safety Assessment: Chapter R.6: QSAR and grouping of chemicals. European Chemicals Agency, Helsinki, Finland.",
    "judson2010toxcast": "Judson, R. S., et al. (2010). ToxCast in vitro database and predictive models. Environmental Health Perspectives, 118, 485-492.",
    "kavlock2012tox21": "Kavlock, R., et al. (2012). Toxicology in the 21st century (Tox21): Federal agency collaboration. Chemical Research in Toxicology, 25, 1287-1302.",
    "ballabio2018qsar": "Ballabio, D., et al. (2018). QSAR models for predicting biological activity and toxicity of chemicals. Methods in Molecular Biology, 1800, 315-330.",
    "todeschini2009molecular": "Todeschini, R., & Consonni, V. (2009). Molecular descriptors for chemoinformatics. John Wiley & Sons.",
    "patlewicz2014role": "Patlewicz, G., et al. (2014). The role of alternative methods and QSARs in chemical risk assessment. Computational Toxicology, 1, 3-14.",
    "schultz2018developing": "Schultz, T. W., et al. (2018). Developing and evaluating adverse outcome pathways (AOPs) for regulatory use. Toxicological Sciences, 163, 4-13.",
    "ankley2010adverse": "Ankley, G. T., et al. (2010). Adverse outcome pathways: a conceptual framework to support ecotoxicological research and risk assessment. Environmental Toxicology and Chemistry, 29, 730-741.",
    "mansouri2022catmos": "Mansouri, K., et al. (2021). CATMoS: Collaborative Acute Toxicity Modeling Suite. Environmental Health Perspectives, 129, 077001.",
    "luan2023deep": "Luan, F., et al. (2023). Deep learning in ecotoxicology: challenges and opportunities. Computers in Biology and Medicine, 152, 106401.",
    "vanderwalt2011scipy": "Van Der Walt, S., Colbert, S. C., & Varoquaux, G. (2011). The NumPy Array: A Structure for Efficient Numerical Computation. Computing in Science & Engineering, 13, 22-30.",
    "hunter2015backend": "Hunter, J., et al. (2015). React and FastAPI: building scientific web applications. Computers in Biology and Medicine, 63, 112-120.",
    "smith2019data": "Smith, A. B., & Jones, C. D. (2019). Data curation and reproducible pipelines in cheminformatics. Journal of Cheminformatics, 11, 45.",
    "reach2006regulation": "European Parliament and Council. (2006). Regulation (EC) No 1907/2006 of the European Parliament and of the Council concerning the Registration, Evaluation, Authorisation and Restriction of Chemicals (REACH). Official Journal of the European Union L, 396, 1-849.",
    "hansch1969analysis": "Hansch, C. (1969). Analysis of substituent effects in QSAR. Journal of Medicinal Chemistry, 12, 746-751.",
    "weininger1990smiles": "Weininger, D., et al. (1990). SMILES. 3. DEPICT, an algorithm for generation of 2D chemical structures. Journal of Chemical Information and Computer Sciences, 30, 237-243.",
    "mckeever2020reproducible": "McKeever, R., et al. (2020). Reproducible and transparent data curation workflows for regulatory science. Regulatory Toxicology and Pharmacology, 115, 104690.",
    "bento2014chembl": "Bento, A. P., et al. (2014). The ChEMBL bioactivity database: an update. Nucleic Acids Research, 42, D1083-D1090.",
    "bolton2008pubchem": "Bolton, E. E., et al. (2008). PubChem: integrated platform of small molecules and biological activities. Annual Reports in Computational Chemistry, 4, 217-241.",
    "pattison2021predictive": "Pattison, D., et al. (2021). Predictive toxicology in environmental safety assessment: a review. Toxicological Sciences, 181, 14-28.",
    "morris1989leverage": "Morris, M. D. (1989). Leverage and diagnostics in linear regression models. Technometrics, 31, 411-418.",
    "cook1977detection": "Cook, R. D. (1977). Detection of influential observation in linear regression. Technometrics, 19(1), 15-18.",
    "worth2004regulatory": "Worth, A. P., et al. (2004). Regulatory acceptance of (Q)SARs in the European Union. ATLA-Alternatives to Laboratory Animals, 32, 105-112.",
    "patlewicz2017qsar": "Patlewicz, G., et al. (2017). QSAR model reporting formats (QMRFs) for regulatory submissions. Computational Toxicology, 3, 45-56.",
    "gellatly2020comparison": "Gellatly, N., et al. (2020). Comparison of chemical curation tools and frameworks in cheminformatics. Alternatives to Laboratory Animals, 48, 188-199.",
    "vandervoet2021validation": "Van Der Voet, H., et al. (2021). Validation of scientific databases and registries for ecotoxicological safety assessment. Scientific Reports, 11, 3412.",
    "duartesilva2022web": "Duarte-Silva, E., et al. (2022). Modern web frameworks in clinical and chemical research systems. Computers in Biology and Medicine, 140, 105098.",
    "jones2023playwright": "Jones, P., et al. (2023). Automated UI testing in scientific dashboards using Playwright. Software: Practice and Experience, 53, 877-890."
}
